version: '3.1'

services:
  basex:
    build: ./dbs/basex
    ports:
      - 1984:1984
      - 8984:8984
      - 8985:8985

  cassandra:
    build: ./dbs/cassandra
    ports:
      - 9042:9042

  mongodb:
    build: ./dbs/mongodb
    ports:
      - 27017:27017

  mysql:
    build: ./dbs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  neo4j:
    build: ./dbs/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  main:
    build: ./
    restart: always
    ports:
      - 4567:4567
    #command: ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target/dbeval-0.0.1.jar"]