version: '3.1'

services:
  arangodb:
   build: ./dbs/arangodb
   ports:
     - 8529:8529
   environment:
     - ARANGO_ROOT_PASSWORD=root

  basex:
    build: ./dbs/basex
    ports:
      - 1984:1984

  cassandra:
    build: ./dbs/cassandra
    ports:
      - 9042:9042

  mongodb:
    build: ./dbs/mongodb
    ports:
      - 27017:27017

  mysql:
    build: ./dbs/mysql
    # Port not specified here since it somehow conflicts
    # Port is 3306 though
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uimadatabase

  neo4j:
    build: ./dbs/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  main:
    build: ./
    restart: always
    ports:
      - 4567:4567
    environment:
      # See README.txt in dbs/arangodb for details on:
      - ARANGODB_HOST=arangodb
      - ARANGODB_PORT=8529
      - ARANGODB_USER=root
      - ARANGODB_PASS=root
      # See README.txt in dbs/basex for details on:
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - BASEX_USER=admin
      - BASEX_PASS=admin
      # See README.txt in dbs/cassandra for details on:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASS=cassandra
      # See README.txt in dbs/mongodb for details on:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=
      - MONGODB_PASS=
      # See README.txt in dbs/mysql for details on:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DBNAME=uimadatabase
    command: ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target.jar"]