version: '3.1'

services:
  arangodb:
   build: ./dbs/arangodb
   ports:
     - 8529:8529
   environment:
     - ARANGO_ROOT_PASSWORD=root

  basex:
    build: ./dbs/basex
    ports:
      - 1984:1984

  cassandra:
    build: ./dbs/cassandra
    ports:
      - 9042:9042

  mongodb:
    build: ./dbs/mongodb
    ports:
      - 27017:27017

  mysql:
    build: ./dbs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  neo4j:
    build: ./dbs/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  main:
    build: ./
    restart: always
    ports:
      - 4567:4567
    environment:
      # See README.txt in dbs/basex for details on:
      - ARANGODB_HOST=arangodb
      - ARANGODB_PORT=8529
      - ARANGODB_USER=root
      - ARANGODB_PASS=root
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - BASEX_USER=admin
      - BASEX_PASS=admin
    command: ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target.jar"]