version: '3.1'

services:
  arangodb:
    build: ./dbs/arangodb
    environment:
     - ARANGO_ROOT_PASSWORD=root

  basex:
    build: ./dbs/basex

  cassandra:
    build: ./dbs/cassandra

  mongodb:
    build: ./dbs/mongodb

  mysql:
    build: ./dbs/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uimadatabase

  neo4j:
    build: ./dbs/neo4j
    environment:
      - NEO4J_AUTH=none

  main:
    build: ./
    ports:
      - 4567:4567
    links:
      - arangodb
      - basex
      - cassandra
      - mongodb
      - mysql
      - neo4j
    volumes:
      - ~/nlpdbeval_data/input/biologie:/code/input
      - ~/nlpdbeval_data/output:/code/output
    environment:
      - INPUT_DIR=/code/input
      - OUTPUT_DIR=/code/output
      - CONFIG_PATH=/code/config.yml
      # See README.txt in dbs/arangodb for details on:
      - ARANGODB_HOST=arangodb
      - ARANGODB_PORT=8529
      - ARANGODB_USER=root
      - ARANGODB_PASS=root
      - ARANGODB_DB=uimadatabase
      # See README.txt in dbs/basex for details on:
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - BASEX_USER=admin
      - BASEX_PASS=admin
      - BASEX_DBNAME=uimadatabase
      # See README.txt in dbs/cassandra for details on:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASS=cassandra
      # See README.txt in dbs/mongodb for details on:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=
      - MONGODB_PASS=
      # See README.txt in dbs/mysql for details on:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DBNAME=uimadatabase
      # See README.txt in dbs/neo4j for details on:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=
      - NEO4J_PASS=