version: '3.1'

services:
  arangodb:
    build: ./dbs/arangodb
    volumes:
      - ./dbs/arangodb/data:/var/lib/arangodb3
    environment:
     - ARANGO_ROOT_PASSWORD=root

  basex:
    build: ./dbs/basex
    volumes:
      - ./dbs/basex/data:/srv/BaseXData

  cassandra:
    build: ./dbs/cassandra
    volumes:
      - ./dbs/cassandra/data:/var/lib/cassandra

  mongodb:
    build: ./dbs/mongodb
    volumes:
      - ./dbs/mongodb/data:/data/db

  mysql:
    build: ./dbs/mysql
    volumes:
      - ./dbs/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=uimadatabase

  neo4j:
    build: ./dbs/neo4j
    volumes:
      - ./dbs/neo4j/data:/var/lib/neo4j/data
    environment:
      - NEO4J_AUTH=none

  main:
    build: ./
    restart: always
    ports:
      - 4567:4567
    links:
      - arangodb
      - basex
      - cassandra
      - mongodb
      - mysql
      - neo4j
    volumes:
      - ./input/biologie:/code/input
      - ./output:/code/output
    environment:
      - INPUT_DIR=/code/input
      - OUTPUT_DIR=/code/output
      - CONFIG_PATH=/code/config.yml
      # See README.txt in dbs/arangodb for details on:
      - ARANGODB_HOST=arangodb
      - ARANGODB_PORT=8529
      - ARANGODB_USER=root
      - ARANGODB_PASS=root
      - ARANGODB_DB=uimadatabase
      # See README.txt in dbs/basex for details on:
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - BASEX_USER=admin
      - BASEX_PASS=admin
      # See README.txt in dbs/cassandra for details on:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASS=cassandra
      # See README.txt in dbs/mongodb for details on:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=
      - MONGODB_PASS=
      # See README.txt in dbs/mysql for details on:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DBNAME=uimadatabase
      # See README.txt in dbs/neo4j for details on:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=
      - NEO4J_PASS=