evaluations:
  - !!dbtest.evaluations.AllWriteEvaluationCase {}
  - !!dbtest.evaluations.AllReadEvaluationCase {}
  - !!dbtest.evaluations.AllQueryEvaluationCase {}
  #- !!dbtest.evaluations.CassandraCounterCreateEvaluationCase {}
  #- !!dbtest.evaluations.CassandraTTREvaluationCase {}
  #- !!dbtest.evaluations.TTREvaluationCase {}
outputProvider: !!dbtest.evaluationFramework.BaseOutputProvider {}